[tool.poetry]
name = "memory-repository"
version = "0.1.0"
description = "A mini social network"
authors = ["Anthony Sergeevich <jespy.kz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.3"
asyncpg = "^0.30.0"
sqlalchemy = "^2.0.36"
pydantic = {extras = ["email"], version = "^2.9.2"}
alembic = "^1.13.3"
pydantic-settings = "^2.6.0"
uvicorn = "^0.32.0"
passlib = "^1.7.4"
pyjwt = "^2.9.0"
httpx = "^0.27.2"
python-multipart = "^0.0.16"


[tool.poetry.group.dev.dependencies]
ruff = "^0.7.0"
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"
pytest-cov = "^6.0.0"

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "*test*"
]

line-length = 79
indent-width = 4

target-version = "py38"

[tool.ruff.lint]
ignore = ["F403", "F405"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
